### PR TITLE
Adds variance to CoRL plots

### PR DESCRIPTION
**Pull request by PFMassiani**
Three functionalities:
* Adds variance to the CoRL plots, with a colorbar that is stabilised along iterations : its amplitude can only increase.
* Automatically compute the gif image using imagemagick's `convert` command.
* Finally, ensures compatibility with NumPy 1.16+ by enforcing the option `allow_pickle=True` when loading pickle files with NumPy.

### CODE REVIEW

**Comment by sheim** [comment]
Can you turn this into an option? We would like to keep the functionality to easily recreate the figures from the paper.

A simple way of doing this is to set the function input to `variance=None`, and then check if it is not `None`. This way the call is overloaded, and will add the variance plot if it is called with this, and won't if it isn't.

**Comment by PFMassiani** [comment]
Sure, it is done.
I'd like to point out that plotting the variance slows down the process of saving the figures a lot: it goes from about 1s to about 20s. This is caused by the fact that the resulting PDFs files are much heavier (without the variances : ~150kB / with the variances : ~3MB). I have not found out why yet.

**Comment by sheim** [comment]
Hmmm the layout also gets kind of screwed up. I think I'll create a _dev_ branch here, and ask you to do the PR to the dev branch. That way we have a working version that we can share, but merge to master only things that are ready for public consumption.

Is it like this on your machine as well? It could be an issue with the backend I'm using (macOS has some issues with the default matplotlib backend).
Screen Shot 2020-04-27 at 15 56 07

**Comment by sheim** [comment]
Okay, so I've created a new `dev` branch, and you can go ahead and make a PR to there. I'll close this for now.

**Pull request closed without merging**
